import type { Metadata } from "next";
import { Geist, Geist_Mono,Arvo } from "next/font/google";
import Sidebar from "@/components/Sidebar/Sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const arvo = Arvo({
  weight: ['400', '700'],
  subsets: ["latin"],
  variable: "--font-arvo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${arvo.variable} antialiased flex  h-screen`}
      >
         <Sidebar/>
        {children}
      </body>
    </html>
  );
}
